= Apereo Notification Portlet

image:https://travis-ci.org/Jasig/NotificationPortlet.svg?branch=master[Linux Build Status]
image:https://ci.appveyor.com/api/projects/status/we2hk9cv24f47oao/branch/master?svg=true[Windows Build status]

This is a https://wiki.jasig.org/display/PLT/Jasig+Sponsored+Portlets[Sponsored Portlet]
in the uPortal project.

https://wiki.jasig.org/pages/viewpage.action?pageId=47875986[Link to old documentation.]

:toc:

== Description

The Notifications Portlet is a JSR-286 notifications portlet originally developed by the University of Manchester.
Notifications from several source are aggregated and grouped by categories in a accordion style view.
The user can drill down into the notifications to get more detailed information.
The notification data sources are configured via xml files. Sample data sources are provided for demonstration purposes.

This project also includes a notification icon and emergency alerts. Notification icon displays the number of notices
currently active. Emergency alerts display urgent notices based on a configured feeds.

== Feature Overview

 * Accordion style display of notifications by categories
 * Selecting a category displays the notifications within that category
 * Selecting a notification within a category replaces the top-level view with a detailed notification view
 * Displays error messages that can be deleted from the view
 * Aggregates notifications from several sources into a single view
 * Can create specialized views by creating custom JSP pages to display other data sources.
   An example student jobs view is included with the portlet.
 * Several notification source integrations, including:
 ** Class Loader Resource
 ** Portlet Event
 ** RESTful JSON
 ** Rome (RSS/Atom)
 ** Student Success Plan
 * Modal view of notifications, as in push-notifications

== Usage / Common Uses

Institutions commonly use notifications for official notices that are important for users to read. These can range from
overdue books to graduation requirements. Rich integration with backend systems can add acknowledgements and other
actions to notices.

Another use is to simply deliver public notices from an RSS/Atom feed to users in the portal.

== User Preferences

Notification portlets do not have user preferences available.

== Installation

This project is published to Maven Central and can be installed with uPortal
using the Portal Overlay Configuration section below.

Note: These notification portlets, include demo emergency portlet, are included with uPortal.

== Configuration

Portlet configuration is broadly divided into two aspects: configuring the portlet application itself, and configuring
the way uPortal interacts with the Notification portlets.

=== Application Configuration

==== Java Properties

Some configuration settings for the Notification portlet are managed in Java properties files that
are loaded by a Spring `PropertySourcesPlaceholderConfigurer`.  (Other settings are data, managed in
the "portlet publication record" a.k.a. `portlet-definition.xml` file;  these are covered elsewhere
in this doc.)

The properties files that are sourced by Spring are:

  - `classpath:datasource.properties`
  - `classpath:configuration.properties`
  - `file:${portal.home}/global.properties`
  - `file:${portal.home}/notification.properties`

For a definitive, comprehensive list of these settings you must look inside `datasource.properties`
and `configuration.properties`.  (This `README` may be incomplete and/or out of date.)

===== The `portal.home` Directory

uPortal version 5 uses a directory called `portal.home` for properties files that live outside of
-- and have the ability to _override_ properties files within-- the webapp in Tommcat.  Please
review the https://github.com/Jasig/uPortal-start/blob/master/README.md[README file for uPortal-Start]
for more information on this sytem.

The Notification portlet sources the shared `global.properties` file, as well as it's own (private)
file called `notification.properties` in the `portal.home` directory.

===== Using Encrypted Property Values

Within the properties files that are sourced by Spring, you may optionally provide sensitive
configuration items -- such as database passwords -- in encrypted format.  Use the
http://www.jasypt.org/cli.html[Jasypt CLI Tools] to encrypt the sensitive value,
then include it in a `.properties` file like this:

```
hibernate.connection.password=ENC(9ffpQXJi/EPih9o+Xshm5g==)
```

Specify the encryption key using the `UP_JASYPT_KEY` environment variable.

=== uPortal Integration (Portlet Definitions)

uPortal integration and related configuration settings are managed as data in the _Portlet Publication
Record_ (the `portlet-definition.xml` file in uPortal). These settings are defined on a per-
publication basis, so you can have several publications of the same portlet with each of them
configured differently.

===== Filtering

You can filter the notices that come from data sources in the publication record.  Use the following
portlet preferences to _exclude_ some notices from appearing in the display:

.Notification Filtering
|===
|Portlet Preference |Possible Value(s)

|FilteringNotificationServiceDecorator.minPriority
|Number between 1 and 5

|FilteringNotificationServiceDecorator.maxPriority
|Number between 1 and 5

|FilteringNotificationServiceDecorator.requiredRole
|Either 'true' or 'false'; a value of 'true' enables role checking, but a notice must define an
      attribute named 'org.jasig.portlet.notice.service.filter.RequiredRoleNotificationFilter.requiredRole'
      to be subject to filtering.
|===

==== Modal Notifications

The `modal` display strategy presents notices in a Bootstrap modal dialog.  If the notice
defines actions, they will be rendered as buttons at the bottom of the dialog;  any button
will dismiss the dialog, as well as invoke the spe,cified action server-side.  Notices that
do not define actions will offer a 'close' (x) option in the upper-right corner of the dialog.
This feature could be used for a Terms of Service pop-up that must be accepted before
accessing the portal.

See notification-portlet-webapp/docs/modal.md[Modal Notifications] for more details.

== Customization

We encourage contribution of new features and enhancements; however, sometimes a feature is truly specific to an
installation. In these cases, we suggest that the Java classes and other suppport files be added to the Notification
Portlet's overlay directory rather than forking a separate Notification Portlet Git repo and customizing it.
This allows for easier upgrades as custom code is clearly separate from the official releases.

== Where to Get Help

The uportal-user@apereo.org mailing list is the best place to go with questions related to Apereo portlets and uPortal.

Issues should be reported at https://issues.jasig.org/browse/NOTIFPLT. Check if your issue has already been reported.
If so, comment that you are also experiencing the issue and add any detail that could help resolve it.
Feel free to create an issue if it has not been reported.
Creating an account is free and can be initiated at the Login widget in the default dashboard.


include::contrib-lic.adoc[]
